import { useEffect, useState } from 'react';
import { Ban, CheckCircle2, Search, Shield, Trash2, UserRound, UsersRound } from 'lucide-react';
import { apiFetch, getErrorMessage } from '../api/client.js';
import { LoadingScreen } from '../components/LoadingScreen.jsx';
import { useAuth } from '../context/AuthContext.jsx';

export function AdminUsersPage() {
  const { user: current } = useAuth(); const [users,setUsers]=useState([]); const [query,setQuery]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  async function load(){setLoading(true);try{setUsers(await apiFetch('/api/admin/users'));}catch(e){setError(getErrorMessage(e));}finally{setLoading(false);}}
  useEffect(()=>{load();},[]);
  async function role(user, next){try{await apiFetch(`/api/admin/users/${user.id}/role`,{method:'PATCH',body:{role:next}});await load();}catch(e){setError(getErrorMessage(e));}}
  async function enabled(user,next){try{await apiFetch(`/api/admin/users/${user.id}/enabled?enabled=${next}`,{method:'PATCH'});await load();}catch(e){setError(getErrorMessage(e));}}
  async function remove(user){if(!confirm(`Удалить пользователя ${user.username}?`))return;try{await apiFetch(`/api/admin/users/${user.id}`,{method:'DELETE'});await load();}catch(e){setError(getErrorMessage(e));}}
  const filtered=users.filter((user)=>`${user.username} ${user.email??''}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="page-section admin-page"><div className="container"><div className="page-heading"><div><span className="eyebrow">Админка / доступ</span><h1>Пользователи</h1><p>Роли и блокировки применяются к активной сессии без задержки.</p></div><div className="header-metric"><UsersRound/><strong>{users.length}</strong><span>учётных записей</span></div></div><div className="admin-toolbar"><div className="input-with-icon"><Search/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Логин или email"/></div></div>{error&&<div className="alert alert--error">{error}</div>}{loading?<LoadingScreen/>:<div className="table-scroll"><table className="data-table admin-table users-table"><thead><tr><th>Пользователь</th><th>Роль</th><th>Статус</th><th>Создан</th><th/></tr></thead><tbody>{filtered.map((user)=><tr key={user.id}><td><div className="user-cell"><span><UserRound/></span><div><strong>{user.username}{user.id===current.id&&<em>вы</em>}</strong><small>{user.email||'Email не указан'}</small></div></div></td><td><select disabled={user.id===current.id} value={user.role} onChange={(e)=>role(user,e.target.value)}><option value="USER">USER</option><option value="ADMIN">ADMIN</option></select></td><td><span className={`status ${user.enabled?'status--published':'status--archived'}`}>{user.enabled?'Активен':'Заблокирован'}</span></td><td>{user.createdAt?new Intl.DateTimeFormat('ru-RU').format(new Date(user.createdAt)):'—'}</td><td className="table-actions">{user.enabled?<button disabled={user.id===current.id} className="icon-button" title="Заблокировать" onClick={()=>enabled(user,false)}><Ban/></button>:<button className="icon-button icon-button--success" title="Разблокировать" onClick={()=>enabled(user,true)}><CheckCircle2/></button>}<button disabled={user.id===current.id} className="icon-button icon-button--danger" title="Удалить" onClick={()=>remove(user)}><Trash2/></button></td></tr>)}</tbody></table></div>}</div></section>;
}
