import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, FileCheck2, Plus, Save, Trash2 } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { apiFetch, getErrorMessage } from '../api/client.js';
import { LoadingScreen } from '../components/LoadingScreen.jsx';

const EMPTY = { manufacturerId: '', slug: '', family: 'PLATE', model: '', seriesName: '', granularity: 'STANDARD_MODEL', status: 'DRAFT', summary: '', applicationCodes: [], materialCodes: [], surfaceAreaM2: '', flowMinM3h: '', flowMaxM3h: '', temperatureMinC: '', temperatureMaxC: '', pressureMaxBar: '', widthMm: '', heightMm: '', depthMm: '', massKg: '', facts: [], sources: [{ title: '', url: '', checkedOn: '2026-07-16', measurementBasis: '' }], pressureLimits: [] };
const numericKeys = ['surfaceAreaM2','flowMinM3h','flowMaxM3h','temperatureMinC','temperatureMaxC','pressureMaxBar','widthMm','heightMm','depthMm','massKg'];
const integerKeys = new Set(['widthMm', 'heightMm', 'depthMm']);

export function AdminEditorPage() {
  const { id } = useParams(); const editing = Boolean(id); const navigate = useNavigate();
  const [form, setForm] = useState(EMPTY); const [lookups, setLookups] = useState({ manufacturers: [], applications: [], materials: [] });
  const [loading, setLoading] = useState(editing); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { apiFetch('/api/heat-exchangers/lookups').then(setLookups).catch((e) => setError(getErrorMessage(e))); if (editing) apiFetch(`/api/admin/heat-exchangers/${id}`).then((item) => setForm({ ...EMPTY, ...item, manufacturerId: item.manufacturer?.id ?? item.manufacturerId, sources: item.sources?.length ? item.sources : EMPTY.sources, facts: item.facts ?? [], pressureLimits: item.pressureLimits ?? [], applicationCodes: item.applicationCodes ?? item.applications?.map((v) => v.code) ?? [], materialCodes: item.materialCodes ?? item.materials?.map((v) => v.code) ?? [] })).catch((e) => setError(getErrorMessage(e))).finally(() => setLoading(false)); }, [id, editing]);
  const title = editing ? `Редактирование: ${form.model}` : 'Новая запись каталога';
  function set(key, value) { setForm((current) => ({ ...current, [key]: value })); }
  function toggleList(key, code) { setForm((current) => ({ ...current, [key]: current[key].includes(code) ? current[key].filter((value) => value !== code) : [...current[key], code] })); }
  function updateSource(index, key, value) { setForm((current) => ({ ...current, sources: current.sources.map((source, i) => i === index ? { ...source, [key]: value } : source) })); }
  function updateFact(index, key, value) { setForm((current) => ({ ...current, facts: current.facts.map((fact, i) => i === index ? { ...fact, [key]: value } : fact) })); }
  const payload = useMemo(() => { const result = { ...form, manufacturerId: Number(form.manufacturerId) }; numericKeys.forEach((key) => { result[key] = form[key] === '' || form[key] == null ? null : Number(String(form[key]).replace(',', '.')); }); return result; }, [form]);
  async function submit(event) { event.preventDefault(); setSaving(true); setError(''); try { await apiFetch(editing ? `/api/admin/heat-exchangers/${id}` : '/api/admin/heat-exchangers', { method: editing ? 'PUT' : 'POST', body: payload }); navigate('/admin/catalog'); } catch (e) { setError(getErrorMessage(e)); } finally { setSaving(false); } }
  if (loading) return <LoadingScreen />;
  return (
    <section className="page-section admin-page"><div className="container admin-editor"><Link className="back-link back-link--dark" to="/admin/catalog"><ArrowLeft /> Каталог</Link><div className="page-heading"><div><span className="eyebrow">Админка / редактор</span><h1>{title}</h1><p>Публикуйте только проверенные данные. Неизвестные значения оставляйте пустыми.</p></div></div>{error && <div className="alert alert--error">{error}</div>}<form onSubmit={submit} className="editor-form">
      <section className="editor-card"><h2>Идентификация</h2><div className="form-grid form-grid--3"><label>Производитель<select required value={form.manufacturerId} onChange={(e) => set('manufacturerId', e.target.value)}><option value="">Выберите</option>{lookups.manufacturers?.map((m) => <option value={m.id} key={m.id}>{m.name}</option>)}</select></label><label>Семейство<select value={form.family} onChange={(e) => set('family', e.target.value)}>{[['PLATE','Пластинчатый'],['SHELL_AND_TUBE','Кожухотрубный'],['AIR_COOLED','Воздушный'],['SPIRAL','Спиральный']].map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></label><label>Гранулярность<select value={form.granularity} onChange={(e) => set('granularity', e.target.value)}><option value="EXACT_CONFIGURATION">Точная конфигурация</option><option value="STANDARD_MODEL">Стандартная модель</option><option value="SERIES">Серия</option></select></label><label>Модель<input required value={form.model} onChange={(e) => set('model', e.target.value)} /></label><label>Серия<input value={form.seriesName ?? ''} onChange={(e) => set('seriesName', e.target.value)} /></label><label>Slug<input required pattern="[a-z0-9-]+" value={form.slug} onChange={(e) => set('slug', e.target.value.toLowerCase())} /></label></div><label>Краткое описание<textarea required rows="3" value={form.summary ?? ''} onChange={(e) => set('summary', e.target.value)} /></label></section>
      <section className="editor-card"><h2>Основные характеристики</h2><div className="form-grid form-grid--4">{numericKeys.map((key) => <label key={key}>{({surfaceAreaM2:'Площадь, м²',flowMinM3h:'Расход min, м³/ч',flowMaxM3h:'Расход max, м³/ч',temperatureMinC:'Температура min, °C',temperatureMaxC:'Температура max, °C',pressureMaxBar:'Макс. давление, bar',widthMm:'Ширина, мм',heightMm:'Высота, мм',depthMm:'Глубина/длина, мм',massKg:'Масса, кг'})[key]}<input type="number" step={integerKeys.has(key) ? '1' : '0.1'} value={form[key] ?? ''} onChange={(e) => set(key, e.target.value)} /></label>)}</div></section>
      <section className="editor-card"><h2>Классификаторы</h2><div className="form-row"><fieldset><legend>Применение</legend><div className="checkbox-grid">{lookups.applications?.map((item) => <label key={item.code}><input type="checkbox" checked={form.applicationCodes.includes(item.code)} onChange={() => toggleList('applicationCodes', item.code)} />{item.name ?? item.label}</label>)}</div></fieldset><fieldset><legend>Материалы</legend><div className="checkbox-grid">{lookups.materials?.map((item) => <label key={item.code}><input type="checkbox" checked={form.materialCodes.includes(item.code)} onChange={() => toggleList('materialCodes', item.code)} />{item.name ?? item.label}</label>)}</div></fieldset></div></section>
      <section className="editor-card"><div className="editor-card__head"><h2>Специальные факты</h2><button type="button" className="button button--secondary button--small" onClick={() => set('facts', [...form.facts, { key: `fact-${form.facts.length + 1}`, label: '', value: '', unit: '' }])}><Plus /> Добавить</button></div>{form.facts.map((fact, index) => <div className="dynamic-row" key={index}><input placeholder="Ключ" value={fact.key ?? ''} onChange={(e) => updateFact(index,'key',e.target.value)} /><input placeholder="Название" value={fact.label ?? ''} onChange={(e) => updateFact(index,'label',e.target.value)} /><input placeholder="Значение" value={fact.value ?? ''} onChange={(e) => updateFact(index,'value',e.target.value)} /><input placeholder="Единица" value={fact.unit ?? ''} onChange={(e) => updateFact(index,'unit',e.target.value)} /><button type="button" className="icon-button icon-button--danger" onClick={() => set('facts', form.facts.filter((_,i) => i !== index))}><Trash2 /></button></div>)}</section>
      <section className="editor-card"><div className="editor-card__head"><h2><FileCheck2 /> Источники</h2><button type="button" className="button button--secondary button--small" onClick={() => set('sources', [...form.sources, { title:'',url:'',checkedOn:'2026-07-16',measurementBasis:'' }])}><Plus /> Добавить</button></div>{form.sources.map((source,index) => <div className="source-editor" key={index}><div className="form-grid form-grid--2"><label>Название<input required value={source.title ?? ''} onChange={(e) => updateSource(index,'title',e.target.value)} /></label><label>HTTPS URL<input required type="url" value={source.url ?? ''} onChange={(e) => updateSource(index,'url',e.target.value)} /></label><label>Дата проверки<input required type="date" value={source.checkedOn ?? ''} onChange={(e) => updateSource(index,'checkedOn',e.target.value)} /></label><label>Основание измерений<input value={source.measurementBasis ?? ''} onChange={(e) => updateSource(index,'measurementBasis',e.target.value)} /></label></div>{form.sources.length > 1 && <button type="button" className="button button--danger button--small" onClick={() => set('sources', form.sources.filter((_,i) => i !== index))}><Trash2 /> Удалить источник</button>}</div>)}</section>
      <div className="editor-actions"><Link className="button button--ghost" to="/admin/catalog">Отмена</Link><button className="button button--primary button--large" disabled={saving}><Save /> {saving ? 'Сохраняем…' : 'Сохранить'}</button></div>
    </form></div></section>
  );
}
