spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    session:
      cookie:
        secure: ${SESSION_COOKIE_SECURE:true}

app:
  security:
    admin:
      username: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
      email: ${ADMIN_EMAIL}
    demo-user:
      enabled: false
